const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:1024,height:768},hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const pos=sessionStorage.getItem('qaPos');if(pos){const s=JSON.parse(localStorage.getItem('bandar-harmoni-v1'));s.position=JSON.parse(pos);localStorage.setItem('bandar-harmoni-v1',JSON.stringify(s));sessionStorage.removeItem('qaPos');}});await p.goto('http://localhost:8080');await p.getByText('Mulakan Pengembaraan',{exact:true}).click();await p.getByText('Jom masuk bandar',{exact:true}).click();await p.getByText('Langkau Cerita',{exact:true}).click();await p.keyboard.down('d');await p.waitForTimeout(500);await p.keyboard.up('d');await p.keyboard.press('Escape');const start=await p.evaluate(()=>JSON.parse(localStorage.getItem('bandar-harmoni-v1')));assert.ok(start.position[0]>.1,'movement');await p.getByRole('button',{name:'Sambung',exact:true}).click();
const data=await p.evaluate(async()=>{const {missions}=await import('./src/missions.js');return missions;});
for(const id of [4,0,2,1,3]){await p.keyboard.press('Escape');await p.evaluate(({id,data})=>{const s=JSON.parse(localStorage.getItem('bandar-harmoni-v1'));sessionStorage.setItem('qaPos',JSON.stringify([data[id].pos[0],data[id].pos[1]+(id===3?-1:1)]));},{id,data});await p.reload();await p.getByText('Sambung Permainan',{exact:true}).click();await p.locator('#interact:not(:disabled)').waitFor();await p.keyboard.press('e');for(let k=0;k<25;k++){const m=await p.evaluate(id=>JSON.parse(localStorage.getItem('bandar-harmoni-v1')).missions[id],id);if(m.stage==='done'){await p.getByRole('button',{name:'Teruskan',exact:true}).click();break;}
if(m.stage==='intro'||m.stage==='resolution'){const res=p.getByText('Lihat dialog penyelesaian',{exact:true});if(await res.count())await res.click();else await p.getByRole('button',{name:'Seterusnya',exact:true}).click();}
else if(m.stage==='action')await p.getByRole('button',{name:data[id].actions[data[id].correct],exact:false}).click();
else if(m.stage==='effect')await p.getByRole('button',{name:data[id].effects[0],exact:false}).click();
else if(m.stage==='reason')await p.getByRole('button',{name:data[id].reasons[0],exact:false}).click();
else if(m.stage==='sentence')await p.getByText('Saya Sudah Terangkan',{exact:true}).click();
else if(m.stage==='emotion')await p.getByRole('button',{name:'Gembira',exact:false}).click();
else if(m.stage==='personal'){const next=p.getByRole('button',{name:'Seterusnya',exact:true});if(await next.count())await next.click();else await p.getByRole('button',{name:'😌 Lega',exact:true}).click();}
}console.log('MISSION',id,'complete');}
assert.match(await p.locator('#stats').innerText(),/100\/100/);assert.match(await p.locator('#stats').innerText(),/15\/15/);await p.screenshot({path:'tests/ending.png'});await p.getByRole('button',{name:'Lihat Sijil',exact:true}).click();assert.match(await p.locator('#certificate').innerText(),/15\/15/);await p.emulateMedia({media:'print'});await p.pdf({path:'tests/certificate.pdf'});await p.emulateMedia({media:'screen'});await p.getByRole('button',{name:'Teroka Bandar',exact:true}).click();await p.keyboard.press('Escape');await p.getByRole('button',{name:'Menu Utama',exact:true}).click();
const reachable=await p.evaluate(async()=>{const {createWorld}=await import('./src/world.js');const w=createWorld(document.createElement('canvas'));const seen=new Set(['0,7']),q=[[0,7]];for(let h=0;h<q.length;h++){const [x,z]=q[h];for(const [a,b]of [[x+1,z],[x-1,z],[x,z+1],[x,z-1]]){const key=a+','+b;if(!seen.has(key)&&w.free(a,b)){seen.add(key);q.push([a,b]);}}}const out={reachable:[[-19,-14],[17,-14],[0,-29],[-18,14],[18,17]].map(v=>seen.has(v.join(','))),wall:!w.free(0,-36),edge:!w.free(40,0),fountain:!w.free(0,0),nodes:seen.size};w.renderer.dispose();return out;});assert.ok(reachable.reachable.every(Boolean));assert.ok(reachable.wall&&reachable.edge&&reachable.fountain);console.log('COLLISIONS',reachable);
await p.setViewportSize({width:390,height:844});await p.getByText('Sambung Permainan',{exact:true}).click();await p.screenshot({path:'tests/mobile.png'});const overflow=await p.evaluate(()=>({body:document.documentElement.scrollWidth>innerWidth,panel:document.querySelector('.panel').scrollWidth>document.querySelector('.panel').clientWidth}));assert.equal(overflow.body,false);assert.equal(overflow.panel,false);assert.deepEqual(errors,[]);console.log('PASS browser 5 missions, 100/15, controls, certificate, collision, portrait; errors',errors);await b.close();})();
