import {missions,emotions,answer,totals} from './missions.js';import {showPanel,el,button,actions} from './ui.js';
export function missionDialogue(ctx,id){const {state,commit,audio,close,world}=ctx,m=state.missions[id],d=missions[id];ctx.talking=id;ctx.stop();
 function frame(speaker,text,step){const p=showPanel('',{cls:'dialogue',close});const top=el('div',undefined,'top');top.append(el('span',d.place+' · '+d.title,'badge'),el('span',step,'progress'));p.append(top);p.append(el('span','🧑','portrait'),el('div',speaker,'speaker'),el('p',text,'speech'));return p;}
 function render(){audio.stop();commit();const stage=m.stage;
 if(stage==='done'){const p=frame(d.names[0],'Terima kasih! Kami akan terus mendengar, berbincang dan menghormati perbezaan.','✅ Selesai');actions(p,button('Teruskan meneroka',close,'primary'));return;}
 if(stage==='intro'||stage==='resolution'){const lines=stage==='intro'?d.intro:d.resolution;const line=lines[Math.min(m.line,lines.length-1)];const p=frame(line[0],line[1],stage==='intro'?'Temui konflik':'Lihat penyelesaian');actions(p,button('🔊 Dengar',()=>audio.speak(line[1])),button('Seterusnya',()=>{m.line++;if(m.line>=lines.length){m.stage=stage==='intro'?'action':'effect';m.line=0;}render();},'primary'));return;}
 if(['action','effect','reason','emotion'].includes(stage)){const prompts={action:'Apakah cadangan kamu untuk membantu mereka?',effect:'Jika mereka terus tidak bertoleransi, apakah kesannya?',reason:'Mengapakah kesan itu mungkin berlaku?',emotion:`Selepas penyelesaian, apakah yang mungkin dirasai oleh ${d.emotion}?`};const opts=stage==='action'?d.actions:stage==='effect'?d.effects:stage==='reason'?d.reasons:emotions;
 const p=frame('Misi kamu',prompts[stage],({action:'1 / 4 · Tindakan',effect:'2 / 4 · Ramalan',reason:'3 / 4 · Alasan',emotion:'4 / 4 · Emosi'})[stage]);if(stage==='reason')p.append(el('div',d.effects[0],'hint'));const c=el('div',undefined,'choices');opts.forEach((text,i)=>{const b=button('',()=>{const ok=answer(state,id,stage,i);commit();audio.effect(ok?'good':'bad');if(ok){if(stage==='action'){ctx.onRestore(id);const q=frame('Pilihan bertoleransi','Bagus! Lihat penduduk mencari penyelesaian bersama-sama. Keharmonian bertambah 10.','🤝 Bandar sedang pulih');actions(q,button('Lihat dialog penyelesaian',render,'primary'));}else if(stage==='emotion'){const q=frame('Hati Harmoni',`${d.emotion} mungkin berasa ${i===0?'gembira':'lega'}. ${d.explain}`,'Perasaan watak');actions(q,button('🔊 Dengar',()=>audio.speak(q.querySelector('.speech').textContent)),button('Seterusnya',render,'primary'));}else render();}else{const explanation=stage==='action'?d.feedback[i]:stage==='effect'?`Fikirkan akibat apabila ${d.names.join(' dan ')} tidak saling mendengar. ${opts[i]} Ini tidak menggambarkan kesan pengabaian toleransi dalam situasi ini.`:stage==='reason'?`${opts[i]} Alasan ini tidak menerangkan keperluan atau keselamatan yang diabaikan.`:'Perasaan ini boleh berlaku dalam kehidupan sebenar. Dalam cerita ini, keperluan watak sudah didengari; fikirkan perasaan selepas persetujuan dicapai.';const q=frame('Mari fikir semula','Cuba fikir semula. Adakah pilihan ini sesuai dengan situasi?','Kamu boleh cuba lagi');q.append(el('p',explanation,'hint'));actions(q,button('🔊 Dengar',()=>audio.speak(explanation)),button('Cuba lagi',render,'primary'));}});b.append(el('b',String.fromCharCode(65+i)),document.createTextNode(text));c.append(b);});p.append(c);actions(p,button('🔊 Dengar',()=>audio.speak(prompts[stage]+'. '+opts.join('. '))));return;}
 if(stage==='sentence'){const sentence=`Saya memilih ${d.effects[0].replace(/\.$/,'').toLowerCase()} kerana ${d.reasons[0].replace(/\.$/,'').toLowerCase()}.`;const p=frame('Saya boleh menerangkan',sentence,'💡 Justifikasi kamu');p.append(el('p','Bacakan ayat ini atau terangkan kepada guru dan rakan dengan kata-kata kamu sendiri.','hint'));actions(p,button('🔊 Dengar Ayat',()=>audio.speak(sentence)),button('Saya Sudah Terangkan',()=>{m.stage='emotion';render();},'primary'));return;}
 if(stage==='personal'){const p=frame('Perasaan kamu','Bagaimanakah perasaan kamu selepas membantu?','Tiada jawapan betul atau salah');const c=el('div',undefined,'choices');emotions.forEach((v,i)=>c.append(button(v,()=>{m.feeling=i;m.stage='done';commit();audio.effect('win');const q=frame('Misi selesai',`Saya berasa ${v.slice(3).trim().toLowerCase()} kerana dapat membantu mereka.`,'✅ +2 Keharmonian');q.append(el('p',`Keharmonian: ${totals(state).harmony}/100. Terima kasih kerana berkongsi perasaan kamu.`));actions(q,button('Teruskan',()=>{close();ctx.afterMission();},'primary'));})));p.append(c);}
 }render();
}
