import {T,createWorld} from './world.js';import {character,animate,input,avatarColors} from './player.js';import {createNPCs} from './npcs.js';import {missions,fresh,totals} from './missions.js';import {read,save} from './storage.js';import {Audio} from './audio.js';import {$,el,button,showPanel,actions,notice,trapFocus,drawMap} from './ui.js';import {missionDialogue} from './dialogue.js';
let world;try{world=createWorld($('world'));}catch(e){const p=showPanel('Paparan 3D tidak tersedia');p.append(el('p','Permainan memerlukan WebGL 2. Cuba pelayar yang menyokong WebGL, aktifkan pecutan perkakasan atau gunakan peranti lain.'));throw e;}
let state=read()||fresh(),running=false,blocked=true,nearest=null,talking=null,ended=false,lastSave=0,stepTime=0,menuOpen=true,previousFocus=null;
const controls=input($('joystick'),$('knob'));const audio=new Audio(state.settings,notice);let player=character(avatarColors[state.avatar],state.avatar);world.scene.add(player);const npcs=createNPCs(world);const focus=new T.Vector3(0,0,-6);let canSave=true;
function positionPlayer(){let [x,z]=state.position;if(!world.free(x,z)){x=0;z=7;}player.position.set(x,0,z);state.position=[x,z];}
positionPlayer();
function commit(){state.position=[player.position.x,player.position.z];const ok=save(state);if(!ok&&canSave)notice('Simpanan tidak tersedia. Kamu masih boleh bermain, tetapi kemajuan mungkin hilang apabila halaman ditutup.');canSave=ok;hud();}
function hud(){const t=totals(state);$('stats').replaceChildren(el('span',`❤️ Harmoni ${t.harmony}/100`),el('span',`⭐ Bintang ${t.stars}/15`),el('span',`🤝 Misi ${t.done}/5`));$('stats').setAttribute('aria-label',`Keharmonian ${t.harmony}, Bintang ${t.stars}, Misi selesai ${t.done}`);$('cityStatus').textContent=t.harmony===100?'Bandar Berjaya Dipulihkan':t.harmony>70?'Bandar Harmoni':t.harmony>40?'Bandar Sedang Pulih':'Bandar Konflik';}
function stop(){blocked=true;controls.clear();$('controls').hidden=true;audio.stop();}
function open(title,options={}){previousFocus=document.activeElement;stop();return showPanel(title,options);}
function close(){audio.stop();$('overlay').replaceChildren();talking=null;blocked=!running;controls.clear();$('controls').hidden=!running;if(running){$('interact').focus();}else menu();}
function applyState(){audio.settings=state.settings;world.scene.remove(player);player=character(avatarColors[state.avatar],state.avatar);world.scene.add(player);positionPlayer();hud();}
function start(){running=true;menuOpen=false;ended=false;$('hud').hidden=false;$('chapter').hidden=false;applyState();if(state.intro<5)story();else {close();if(totals(state).done===5)ending();}}
function menu(){stop();menuOpen=true;running=false;$('hud').hidden=true;$('chapter').hidden=true;$('minimap').hidden=true;const p=showPanel('',{cls:'menu'});p.append(el('span','PENDIDIKAN MORAL · TAHUN 5','eyebrow'),el('h1','BANDAR\nHARMONI'),el('div','MISI WIRA TOLERANSI','subtitle'),el('span','✦ Pengembaraan bandar 3D','badge'));const b=el('div',undefined,'menuButtons');b.append(button('Mulakan Pengembaraan',()=>{audio.start();if(read())confirmReset(avatarMenu);else avatarMenu();},'primary'));const resume=button('Sambung Permainan',()=>{audio.start();state=read()||fresh();start();});resume.disabled=!read();b.append(resume,button('Cara Bermain',help),button('Tetapan Bunyi',settings),button('Panduan Guru',teacher));p.append(b,el('p','Teroka · Dengar · Bincang · Pulihkan','foot'));}
function confirmReset(next){const p=open('Mulakan semula?',{close:()=>running?close():menu()});p.append(el('p','Kemajuan permainan ini akan digantikan selepas kamu memulakan pengembaraan baharu.'));actions(p,button('Batal',()=>running?close():menu()),button('Ya, pengembaraan baharu',next,'danger'));}
function avatarMenu(){const p=open('Pilih wira kamu',{close:menu});p.append(el('p','Semua wira boleh membantu Bandar Harmoni. Nama sebenar tidak diperlukan.'));let selected=0;const av=el('div',undefined,'avatars');['Rimba','Suria','Bayu','Bintang'].forEach((name,i)=>{const b=button('',()=>{selected=i;av.querySelectorAll('button').forEach((x,j)=>x.setAttribute('aria-pressed',String(j===i)));});b.setAttribute('aria-pressed',String(i===0));b.append(el('span',['🧑🏽','👩🏽','🧑🏻','👩🏻'][i],'avatar-icon'),document.createTextNode(name));av.append(b);});p.append(av);const label=el('label','Nama panggilan (pilihan)','field'),name=el('input');name.maxLength=24;name.placeholder='Wira';label.append(name);p.append(label);actions(p,button('Jom masuk bandar',()=>{const preferences={...state.settings};state=fresh();state.settings=preferences;state.avatar=selected;state.name=name.value.trim()||'Wira';applyState();commit();start();},'primary'));}
const storyLines=['Selamat datang ke Bandar Harmoni! Dahulu, penduduk di sini hidup aman dan saling membantu.','Sekarang, beberapa penduduk sukar menerima perbezaan dan tidak mahu bertolak ansur.','Bolehkah kamu membantu mereka berbincang dan mencari penyelesaian?','Saya akan cuba membantu!','Cari tanda ⚡ di peta. Dekati penduduk, kemudian tekan Berinteraksi.'];
function story(){stop();const p=showPanel('',{cls:'dialogue'});p.append(el('div',state.intro===3?state.name:'Kak Hana','speaker'),el('p',storyLines[state.intro],'speech'));actions(p,button('Langkau Cerita',()=>{state.intro=5;commit();close();}),button('🔊 Dengar',()=>audio.speak(storyLines[state.intro])),button('Seterusnya',()=>{state.intro++;commit();state.intro<5?story():close();},'primary'));}
function help(){const p=open('Cara Bermain',{close:()=>running?close():menu()});p.append(el('p','Teroka Bandar → Temui Konflik → Pilih Dialog → Ramalkan Kesan → Berikan Alasan → Kenal Pasti Emosi → Pulihkan Bandar.'));for(const txt of ['Komputer: WASD atau anak panah untuk berjalan. E atau Space untuk berinteraksi apabila dekat. Escape untuk jeda.','Tablet: gerakkan joystick di kiri dan sentuh Berinteraksi di kanan. Kedua-duanya menerima sentuhan serentak.','Lima lokasi boleh dikunjungi mengikut pilihan kamu. Buka Peta dan Buku Misi untuk mencari penduduk.','Keharmonian menunjukkan pemulihan bandar: bermula 40, bertambah 12 setiap misi. Bintang menunjukkan pencapaian percubaan pertama. Kamu masih boleh mencapai 100 keharmonian walaupun kurang daripada 15 bintang.','Toleransi ialah mendengar, menghormati perbezaan dan bertolak ansur secara wajar. Kita tidak membiarkan perbuatan berbahaya atau menafikan hak orang lain.'])p.append(el('p',txt,'hint'));actions(p,button('Faham',()=>running?close():menu(),'primary'));}
function settings(){const p=open('Tetapan Bunyi & Paparan',{close:()=>running?close():menu()});for(const [key,title]of [['music','Muzik latar'],['sfx','Kesan bunyi'],['reduced','Kurangkan animasi']]){const l=el('label',title,'toggle');const c=el('input');c.type='checkbox';c.checked=state.settings[key];c.onchange=()=>{state.settings[key]=c.checked;audio.start();commit();};l.append(c);p.append(l);}p.append(el('p','Butang Dengar menggunakan suara yang tersedia pada peranti. Semua arahan turut disediakan sebagai teks.','hint'));actions(p,button('Selesai',()=>running?close():menu(),'primary'));}
function rows(p){state.missions.forEach((m,i)=>{const row=el('div',undefined,'missionRow');const text=el('div',`${i+1}. ${missions[i].place}`);const s=m.stage==='done'?'✅ Selesai':m.stage==='intro'&&!m.line?'⚡ Belum dibantu':'💬 Sedang dibantu';text.append(el('small',missions[i].title+' · '+s));const stars=(m.passed.action&&m.attempts.action===1?1:0)+(m.passed.reason&&m.attempts.reason===1&&m.attempts.effect===1?1:0)+(m.passed.emotion&&m.attempts.emotion===1?1:0);row.append(text,el('span',`⭐ ${stars}/3`));p.append(row);});}
function book(){const p=open('Buku Misi',{close});p.append(el('p','Kunjungi mana-mana lokasi. Perbualan yang belum selesai boleh disambung dengan mendekati penduduk semula.','hint'));rows(p);p.append(el('p','⭐ Pilihan Bijak: tindakan pertama sesuai. ⭐ Pemikir Bijak: kesan dan alasan pertama sesuai. ⭐ Hati Harmoni: emosi pertama sesuai.','tiny'));actions(p,button('Teruskan meneroka',close,'primary'));}
function teacher(){const p=open('Panduan Guru',{cls:'wide',close:()=>running?close():menu()});p.append(el('p','Pendidikan Moral Tahun 5 · Anggaran 15–25 minit','badge'));for(const [h,t]of [['Fokus pembelajaran','SP 14.3: Justifikasi kesan pengabaian toleransi. SP 14.4: Ekspresi perasaan. SP 14.5: Latihan mengamalkan toleransi.'],['Cara mengendalikan','2 minit penerokaan dan arahan; kira-kira 3 minit setiap misi; 3–5 minit refleksi. Individu atau kumpulan kecil: lantik pengawal, pembaca dan penerang. Tukar peranan setiap misi. Jika berkongsi satu iPad, gilirkan kumpulan di lokasi berlainan.'],['Soalan lisan','Apakah keperluan setiap watak? Jika mereka tidak bertolak ansur, mengapakah hubungan terjejas? Adakah cadangan kamu adil dan selamat? Bagaimanakah kamu tahu watak mungkin berasa lega?'],['Pentaksiran sebenar','Pilihan dalam permainan memberi peluang berlatih. Pengamalan toleransi sebenar perlu diperhatikan semasa murid berbincang, berkongsi peranti dan menunggu giliran. Bintang bukan satu-satunya ukuran kefahaman.'],['Sokongan membaca','Gunakan Dengar jika suara tersedia. Guru atau rakan boleh membacakan ayat, kemudian minta murid menerangkan sebab dengan kata-kata sendiri.']]){p.append(el('h3',h),el('p',t));}p.append(el('h3','Pencapaian semasa'));rows(p);state.missions.forEach((m,i)=>p.append(el('p',`${i+1}. Percubaan tindakan ${m.attempts.action}, kesan ${m.attempts.effect}, alasan ${m.attempts.reason}, emosi ${m.attempts.emotion}.`,'tiny')));actions(p,button('Kembali',()=>running?close():menu(),'primary'),button('Mula semula',()=>confirmReset(avatarMenu),'danger'));}
function pause(){const p=open('Permainan dijeda',{close});p.append(el('p','Kemajuan disimpan secara automatik pada peranti ini. Kamu boleh berehat tanpa kehilangan markah.'));actions(p,button('Sambung',close,'primary'),button('Cara Bermain',help),button('Panduan Guru',teacher),button('Menu Utama',()=>{commit();menu();}));if(totals(state).done===5)actions(p,button('Lihat Sijil',certificate));commit();}
function ending(){ended=true;stop();const p=showPanel('🏆 WIRA TOLERANSI',{cls:'wide'});const score=totals(state);p.append(el('p','Tahniah! Kamu berjaya memulihkan Bandar Harmoni!','speech'),el('div',`⭐ ${score.stars}/15 · ❤️ ${score.harmony}/100 · 🤝 ${score.done}/5`,'summary'),el('p','Kak Hana: Kamu telah membantu penduduk mendengar, berbincang dan menghormati perbezaan. Teruskan amalan toleransi di sekolah dan dalam masyarakat!'));const l=el('label','Hari ini saya belajar bahawa toleransi ialah…','field'),select=el('select');for(const t of ['Mendengar pandangan orang lain.','Menghormati perbezaan.','Berbincang untuk mencapai persetujuan.'])select.append(el('option',t));select.value=state.reflection||select.options[0].value;state.reflection=select.value;select.onchange=()=>{state.reflection=select.value;commit();};l.append(select);p.append(l);const l2=el('label','Satu amalan toleransi yang akan saya lakukan ialah…','field'),promise=el('textarea');promise.rows=2;promise.maxLength=200;promise.placeholder='Contoh: Saya akan mendengar pandangan rakan sebelum membuat keputusan.';promise.value=state.promise;promise.oninput=()=>{state.promise=promise.value;commit();};l2.append(promise);p.append(l2);actions(p,button('Lihat Sijil',()=>{commit();certificate();},'primary'),button('Teroka Bandar',close),button('Main Semula',()=>confirmReset(avatarMenu)));commit();audio.effect('win');}
function certificate(){stop();$('overlay').replaceChildren();const c=$('certificate');c.hidden=false;c.className='certificate-screen';c.replaceChildren(el('p','PENDIDIKAN MORAL · TAHUN 5','eyebrow'),el('h1','SIJIL WIRA TOLERANSI'),el('p','BANDAR HARMONI 3D'),el('p','Diberikan kepada'),el('div',state.name,'name'),el('p','kerana berjaya membantu penduduk memulihkan keharmonian bandar.'),el('div',`⭐ ${totals(state).stars}/15 bintang · ❤️ 100/100 keharmonian · 🤝 5/5 misi`,'summary'),el('p','“Mendengar, berbincang dan menghormati perbezaan.”'));if(state.promise)c.append(el('p','Amalan saya: '+state.promise));c.append(el('p','Sijil penyertaan aktiviti pembelajaran · '+new Date().toLocaleDateString('ms-MY'),'tiny'));const a=actions(c,button('Cetak / Simpan sebagai PDF',()=>window.print(),'primary'),button('Teroka Bandar',()=>{c.hidden=true;close();}),button('Kembali ke refleksi',()=>{c.hidden=true;ending();}));a.classList.add('no-print');c.querySelector('button').focus();}
function interact(){nearest=npcs.nearest(player);if(blocked||!nearest)return;audio.start();controls.clear();if(nearest.mission<0){const p=open('Kak Hana',{close});p.append(el('p',totals(state).done===5?'Terima kasih, Wira! Teruskan amalan toleransi setiap hari.':'Cari lima lokasi bertanda ⚡. Dengar keperluan setiap orang dan bantu mereka mencapai persetujuan. Toleransi tidak bermaksud membiarkan perbuatan berbahaya.','speech'));actions(p,button('Teruskan',close,'primary'));return;}
 const ctx={state,commit,audio,close,world,stop,onRestore:()=>{talking=null;},afterMission:()=>{if(totals(state).done===5&&!ended)ending();},set talking(v){talking=v;}};missionDialogue(ctx,nearest.mission);}
$('interact').onclick=interact;$('mapBtn').onclick=()=>{$('minimap').hidden=!$('minimap').hidden;$('mapBtn').setAttribute('aria-expanded',String(!$('minimap').hidden));};$('bookBtn').onclick=book;$('audioBtn').onclick=settings;$('pauseBtn').onclick=pause;
addEventListener('keydown',e=>{trapFocus(e);if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'&&running&&$('certificate').hidden){e.preventDefault();if(blocked)close();else pause();}if(!blocked&&(e.code==='KeyE'||(e.code==='Space'&&e.target.tagName!=='BUTTON'))){e.preventDefault();interact();}});
addEventListener('blur',()=>{controls.clear();audio.stop();if(running&&!blocked)pause();});document.addEventListener('visibilitychange',()=>{controls.clear();audio.stop();if(document.hidden&&running){commit();if(!blocked)pause();}});addEventListener('pagehide',()=>{if(running)commit();});
let previous=performance.now(),elapsed=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-previous)/1000,.05);previous=now;if(document.hidden)return;elapsed+=dt;const score=totals(state);let moving=false;
 if(running&&!blocked){const v=controls.vector();moving=v.moving;if(moving){const nx=player.position.x+v.x*7*dt,nz=player.position.z+v.z*7*dt;if(world.free(nx,player.position.z))player.position.x=nx;if(world.free(player.position.x,nz))player.position.z=nz;player.rotation.y=Math.atan2(v.x,v.z);stepTime+=dt;if(stepTime>.36){stepTime=0;audio.effect('step');}}lastSave+=dt;if(lastSave>2){lastSave=0;commit();}}
 animate(player,elapsed,moving,state.settings.reduced);nearest=npcs.nearest(player);$('interact').disabled=!nearest||blocked;$('interact').textContent=nearest?`💬 ${nearest.name} · Berinteraksi`:'💬 Dekati penduduk';
 npcs.update(dt,elapsed,state,talking,score.done===5);world.update(dt,elapsed,state,score.harmony);const target=menuOpen?new T.Vector3(Math.sin(elapsed*.05)*4,0,-8):player.position;focus.lerp(target,state.settings.reduced?1:1-Math.exp(-dt*4));world.camera.position.copy(focus).add(new T.Vector3(26,32,26));world.camera.lookAt(focus);world.renderer.render(world.scene,world.camera);if(!$('minimap').hidden)drawMap($('minimap'),player,missions,state);audio.update(dt,running&&!blocked);}
hud();menu();requestAnimationFrame(frame);
