import {T,box} from './world.js';
export const avatarColors=[0x427f79,0xb87e60,0x797ead,0xd3aa52];
export function character(color=avatarColors[0],variant=0){const g=new T.Group();box(g,0,1,0,.7,.9,.45,color);box(g,0,1.78,0,.65,.65,.6,[0xdba778,0xb77e55,0xe1b48f,0xbf916c][variant%4]);box(g,0,2.1,0,.7,.2,.64,0x4c463b);box(g,0,1.98,-.26,.7,.35,.15,0x4c463b);for(const x of [-.15,.15])box(g,x,1.82,.31,.07,.08,.03,0x313831);const legs=[box(g,-.2,.35,0,.25,.65,.3,0x45586a),box(g,.2,.35,0,.25,.65,.3,0x45586a)];const arms=[box(g,-.5,1,0,.22,.8,.25,color),box(g,.5,1,0,.22,.8,.25,color)];const shadow=new T.Mesh(new T.CircleGeometry(.65,12),new T.MeshBasicMaterial({color:0x45654c,transparent:true,opacity:.23,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.02;g.add(shadow);g.userData={legs,arms};return g;}
export function animate(g,t,moving,reduced=false){g.userData.legs.forEach((l,i)=>l.rotation.x=reduced?0:moving?Math.sin(t*10+i*Math.PI)*.55:0);g.userData.arms.forEach((l,i)=>l.rotation.x=reduced?0:moving?Math.sin(t*10-i*Math.PI)*.4:Math.sin(t*1.7)*.04);}
export function input(joystick,knob){const keys=new Set();const stick={x:0,y:0};let pointer=null;function clear(){keys.clear();pointer=null;stick.x=stick.y=0;knob.style.transform='translate(0,0)';}addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
 function move(e){if(pointer!==e.pointerId)return;const r=joystick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.hypot(x,y),scale=Math.min(1,45/(len||1));stick.x=x*scale/45;stick.y=y*scale/45;knob.style.transform=`translate(${stick.x*35}px,${stick.y*35}px)`;}
 joystick.addEventListener('pointerdown',e=>{pointer=e.pointerId;joystick.setPointerCapture(pointer);move(e);});joystick.addEventListener('pointermove',move);for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,e=>{if(pointer===e.pointerId)clear();});addEventListener('blur',clear);
 return {clear,vector(){let x=stick.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=stick.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}return {x:(x+y)*Math.SQRT1_2,z:(y-x)*Math.SQRT1_2,moving:len>.05};}};
}
